# Generated by Django 5.0.2 on 2024-03-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimientos',
            name='Requerimiento',
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='fechaPruebas',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='requerimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
