# Generated by Django 5.0.2 on 2024-03-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_requerimientos_requerimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientos',
            name='fechaPruebas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
