# Generated by Django 5.0.2 on 2024-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alianzasolicitante_areasolicitante_estado_mediocarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='sprintDesarrollo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
