# Generated by Django 5.0.2 on 2024-03-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_requerimientos_sprintdesarrollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='medioCarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.mediocarga'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='sprintDesarrollo',
            field=models.CharField(choices=[('Sin Sprint', 'Sin Sprint'), ('Enero', 'Enero'), ('Febrero', 'Febrero')], default='Sin Sprint', max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='ticket',
            field=models.CharField(max_length=100, verbose_name='# Ticket'),
        ),
    ]
