# Generated by Django 5.0.2 on 2024-03-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_requerimientos_mediocarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='alianzaSolicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.alianzasolicitante'),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='areaSolicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.areasolicitante'),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.estado'),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='pasoProduccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='plataforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.plataforma'),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.responsable'),
        ),
        migrations.AlterField(
            model_name='alianzasolicitante',
            name='alianzaSolicitante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='areasolicitante',
            name='areaSolicitante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mediocarga',
            name='medioCarga',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='medioCarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.mediocarga'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='responsable',
            field=models.CharField(max_length=50),
        ),
    ]
