# Generated by Django 5.0.2 on 2024-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_requerimientos_alianzasolicitante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alianzasolicitante',
            old_name='alianzaSolicitante',
            new_name='alianzasolicitante',
        ),
        migrations.RenameField(
            model_name='areasolicitante',
            old_name='areaSolicitante',
            new_name='areasolicitante',
        ),
        migrations.RenameField(
            model_name='mediocarga',
            old_name='medioCarga',
            new_name='mediocarga',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='alianzaSolicitante',
            new_name='alianzasolicitante',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='areaSolicitante',
            new_name='areasolicitante',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='fechaActualizacion',
            new_name='fechaactualizacion',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='fechaCreacion',
            new_name='fechacreacion',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='fechaPruebas',
            new_name='fechapruebas',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='fechaRegistro',
            new_name='fecharegistro',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='medioCarga',
            new_name='mediocarga',
        ),
        migrations.RenameField(
            model_name='requerimientos',
            old_name='sprintDesarrollo',
            new_name='sprintdesarrollo',
        ),
        migrations.RemoveField(
            model_name='requerimientos',
            name='pasoProduccion',
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='pasosroduccion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Paso Producción'),
        ),
    ]
