# Generated by Django 5.0.2 on 2024-03-08 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_fechaactualizacion_requerimientos_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alianzasolicitante',
            name='alianzasolicitante',
            field=models.CharField(max_length=50, verbose_name='Alianza'),
        ),
        migrations.AlterField(
            model_name='areasolicitante',
            name='areasolicitante',
            field=models.CharField(max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mediocarga',
            name='mediocarga',
            field=models.CharField(max_length=50, verbose_name='Medio De Carga'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='plataforma',
            field=models.CharField(max_length=50, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='responsable',
            field=models.CharField(max_length=50, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100, verbose_name='# Identificacion')),
                ('nombrecompleto', models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo')),
                ('fechaingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
