# Generated by Django 5.0.2 on 2024-03-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_requerimientos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requerimientos',
            table='requerimientos',
        ),
    ]
