# Generated by Django 5.0.2 on 2024-04-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_requerimientos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediocarga', models.CharField(max_length=50, verbose_name='Medio De Carga')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pruebas',
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'responsable', 'verbose_name_plural': 'Responsables'},
        ),
        migrations.AlterModelTable(
            name='responsable',
            table='responsables',
        ),
        migrations.DeleteModel(
            name='Activos',
        ),
    ]
