# Generated by Django 5.0.2 on 2024-04-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_mediocar_remove_activos_user_delete_pruebas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasolicitante',
            options={'verbose_name': 'area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelTable(
            name='areasolicitante',
            table='area_solicitante',
        ),
    ]
