# Generated by Django 5.0.2 on 2024-04-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_areasolicitante_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedioCar',
        ),
        migrations.AlterModelOptions(
            name='alianzasolicitante',
            options={'verbose_name': 'alianza', 'verbose_name_plural': 'Alianzas'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'estados', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='mediocarga',
            options={'verbose_name': 'medio', 'verbose_name_plural': 'Medios De Carga'},
        ),
        migrations.AlterModelOptions(
            name='plataforma',
            options={'verbose_name': 'plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
        migrations.AlterModelTable(
            name='alianzasolicitante',
            table='alianza_solicitante',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='estados_requerimientos',
        ),
        migrations.AlterModelTable(
            name='mediocarga',
            table='medio_carga_requerimientos',
        ),
        migrations.AlterModelTable(
            name='plataforma',
            table='plataforma_requerimientos',
        ),
    ]
