# Generated by Django 5.0.2 on 2024-04-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_delete_mediocar_alter_alianzasolicitante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alianzasolicitante',
            table='alianza_solicitante_requerimientos',
        ),
        migrations.AlterModelTable(
            name='areasolicitante',
            table='area_solicitante_requerimientos',
        ),
        migrations.AlterModelTable(
            name='responsable',
            table='responsables_requerimientos',
        ),
    ]
