# Generated by Django 5.0.2 on 2024-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_alianzasolicitante_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='correo',
            field=models.EmailField(default='', max_length=100, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
    ]
